#lang racket/base

(provide glossary-terms-dictionary)

(define glossary-terms-dictionary
  '(("accessor functions" "functions to extract values from a data structure")
    ("apply" "use a given function on some inputs")
    ("arguments" "the inputs to a function; expressions for arguments follow the name of a function")
    ("booleano" "um tipo de dado com dois valores: verdadeiro/true ou falso/false")
    ("círculo de avaliação" "um diagrama da estrutura de uma expressão (aritmética ou em código)")
    ("clause" "a question and its corresponding answer in a conditional expression")
    ("condicional" "uma expressão em código feita de perguntas e respostas")
    ("assinatura" "uma declaração com o nome, domínio, e imagem de uma função")
    ("data structure" "A group of values that can be returned as a single datatype")
    ("define" "associate a descriptive name with a value")
    ("definitions window" "the text box at the top of the Editor (DrRacket or WeScheme), where definitions for values and functions are written")
    ("receita de projeto" "uma sequência de passos que ajudam pessoas a documentar, testar, e escrever funções")
    ("domínio" "o tipo de dado que a função espera receber")
    ("editor" "software in which you can write and evaluate code")
    ("mensagem de erro" "informação do computador sobre erros no código")
    ("evaluate" "perform the computation in an expression, producing an answer")
    ("evaluates to" "the result of computing an expression")
    ("exemplo" "mostra o uso de uma função com entradas específicas e o que a função deve calcular com essas entradas")
    ("expression" "a computation written in the rules of some language (such as arithmetic, code, or a Circle of Evaluation)")
    ("definição de função" "código que nomeia uma função, lista suas variáveis, e prepara a expressão para ser usada quando a função for chamada")
    ("função" "um objeto matemático que recebe algo como entrada e produz uma saída")
    ("hipotenusa" "o lado oposto ao ângulo de 90-graus em um triângulo-retângulo")
    ("figura" "um tipo de dado para figuras")
    ("interactions window" "the text box at the top of the Editor (DrRacket or WeScheme), where we enter expressions to evaluate")
    ("legal expression" "code that follows the Code Rules for a language")
    ("expressão matemática" "um cálculo matemático")
    ("piecewise function" "a function that computes different expressions based on its input")
    ("nome" "como nós nos referimos a uma função ou valor definido na linguagem (exemplos: +, *, star, circle)")
    ("produce" "to compute a value from an expression")
    ("linguagem de programação" "um conjunto de regras para escrever código que um computador possa calcular") 
    ("declaração de propósito" "uma breve descrição do que a função faz")
    ("imagem" "o tipo de dado que a função produz")
    ("string" "qualquer sequência de caracteres entre aspas (exemplos:\"olá\", \"42\", \"isto é uma string!\")")
    ("tipo" "refere-se a um tipo geral de dado, como Número, String, Figura ou Booleano")
    ("unit test" "an example showing the use of a function with a specific value or values, and the answer it should produce")
    ("valor" "uma parte específica de dado, como 5 ou \"olá\"")
    ("variável" "algo que muda")
    ("nome de variável" "nome de uma informação que pode ser diferente cada vez que a função é utilizada")
   ))